baseURL = "https://seraph.ws/"
languageCode = "en-us"
title = "Seraph"
theme = "terminal"
publishDir = "public"


[params]
  author = "Your Name"
  description = "Personal portfolio and blog"
  showReadingTime = true
  github = "https://github.com/more-robots-please"
  customCSS = ["terminal.css"]
  favicon = "favicon.svg"

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about"
  weight = 1
  
[[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects"
  weight = 2
